### ISSUE TITLE
Augment ember-cli-htmlbars to discover and apply new `glimmer-ast-plugin`s from the registry

### ISSUE THREAD

**Issue by amiller-gh** [linkedin/css-blocks#123]
CSS Blocks delivers a `glimmer-ast-plugin` to transform templates with rewritten class names and logic.

We currently register this plugin with the registry [here](https://github.com/linkedin/css-blocks/blob/master/packages/%40css-blocks/ember-cli/index.js#L24).

We did the work to augment `@glimmer/glimmer-application-pipeline` to automatically discover and apply `glimmer-ast-plugin`s from the registry in https://github.com/glimmerjs/glimmer-application-pipeline/pull/145

We need to make this same type of change in https://github.com/ember-cli/ember-cli-htmlbars so our `glimmer-ast-plugin` is applied.

**Comment by Turbo87** [comment]
as you can see e.g. at https://github.com/simplabs/ember-test-selectors/blob/d7487e0fa326c7f50217278cc50be3fbd7bdfe6f/index.js#L33-L38 it is already possible to register handlebars AST transforms, but for some reason the registry key is different
