### ISSUE TITLE
props / params in example on website 

### ISSUE THREAD

**Issue by DanielRuf** [linkedin/css-blocks#133]
In the example on the website there is `size, inverse, icon, children` defined as parameters.
But in the compile step it says `size, color, icon, children`

I guess this is not correct as color is nowhere used or defined.

**Comment by amiller-gh** [comment]
Fixed #134 🎉

**Comment by DanielRuf** [comment]
When will this be deployed to the website?

**Comment by DanielRuf** [comment]
Or did I oversee something?
