### ISSUE TITLE
React example on css-blocks.com has incorrect class keys

### ISSUE THREAD

**Issue by scottwarren** [linkedin/css-blocks#138]
On the home page of css-blocks.com, in the example section for the `template.jsx` file, there are `class` attributes in the JSX (which should be `className` instead):

```
  // ..
    return (
        <button class={style}>
            {icon && <span class={styles.icon}>{icon}</span>}
            {children}
        </button>
    )
  // ..
```

should be, instead:

```
  // ..
    return (
        <button className={style}>
            {icon && <span className={styles.icon}>{icon}</span>}
            {children}
        </button>
    )
  // ..
```

FWIW, I did a little search, but I couldn't seem to find a branch to make these changes myself, sorry!

**Comment by amiller-gh** [comment]
Good catch! We actually already had a PR to fix this in the docs and its already pulled in to master 🙂 We just need to re-deploy the website, which will happen later today.

Closing as a duplicate – thanks for opening the issue!

**Comment by amiller-gh** [comment]
(We're in the process of setting up CD for the website / API docs)

**Comment by scottwarren** [comment]
No worries -- thanks for the reply 👍 😁
