### ISSUE TITLE
Intro site appears to have typo

### ISSUE THREAD

**Issue by dcwither** [linkedin/css-blocks#140]
Hi I started by looking at your example on http://css-blocks.com/ and I noticed what I think is a typo in the code example.

The first step (Code) has a prop `inverse` but in the next step (Compile), that prop is missing and in its place is `color` but the `inverse` prop is still used.

![props typo](https://user-images.githubusercontent.com/1641405/39262901-99ca5968-4875-11e8-81b5-67280aa25ffe.png)

This project looks really exciting btw!

**Comment by amiller-gh** [comment]
This has been fixed, thank you for calling it out! 😁
