### ISSUE TITLE
CONTRIBUTING.md 

### ISSUE THREAD

**Issue by bahtou** [linkedin/css-blocks#147]
Following the steps here
https://github.com/linkedin/css-blocks/blob/master/CONTRIBUTING.md

When I run the script `./scripts/checkout-opticss-and-link.sh` I get the following error

Error: Cannot find module '/<blahblah>/projects/opticss/lerna.json'

Is there a step that is missing in the docs?

**Comment by chriseppstein** [comment]
Now that the OptiCSS code is released, you can safely skip that step. Just the following is necessary:

1. `git clone https://github.com/linkedin/css-blocks.git`
2. `cd css-blocks`
3. `lerna bootstrap`
4. `lerna run test`

I'll update the document.

**Comment by bahtou** [comment]
great 👍 up and running
