### ISSUE TITLE
Analyzer not finding correct entry path with webpack-dev-server

### ISSUE THREAD

**Issue by TomiS** [linkedin/css-blocks#163]
Hi. I tried to install css-blocks in our environment that has Flow-typed React 16 code running on Webpack 3 and Babel 6. We're using webpack-dev-server for serving the app in dev. It seems the Analyzer plugin does not find the correct entry point but thinks the webpack-dev-server folder is the root folder (error below)
`
ERROR in [css-blocks] JSXParseError: Cannot read JSX entry point file /Users/myname/Documents/myapp/node_modules/webpack-dev-server/client/index.js?http:/localhost:3000: ENOENT: no such file or directory, open '/Users/myname/Documents/myapp/node_modules/webpack-dev-server/client/index.js?http:/localhost:3000' (/Users/myname/Documents/myapp/node_modules/webpack-dev-server/client/index.js?http:/localhost:3000)
`

Correct path would be:
 `/Users/myname/Documents/myapp/client/main.js`

I have this config in webpack config:
```js
  const analyzerInstance = new CssBlocks.Analyzer('client/main.js', {
    baseDir: '/Users/myname/Documents/myapp',
    types: 'flow',
  });
```
but it doesn't seem to have effect.

ps. Both our app and webpack-dev-server happen to use `client` folder as part of the path.  So `client/index.js` is not mistyped path to our entry but the actual entry point of the dev server. (I was confused by this myself for a second)

**Comment by chriseppstein** [comment]
Can you publish a minimal app that reproduces this problem somewhere so I can try to debug it?

**Comment by TomiS** [comment]
Hey again @chriseppstein. I created this repo: https://github.com/TomiS/css-blocks-test
(run `yarn install` and `yarn run dev` on master)

I tried for a while to do some creative copy-pasting from the css-blocks website's webpack config. But I'm just not able to get rid of `JSXParseError`s when css-blocks is in use. If I remove all css-blocks related config, the build works. Any thoughts would be greatly appreciated.

**Comment by chriseppstein** [comment]
@TomiS Thanks. I'll investigate!

**Comment by fforres** [comment]
@TomiS @chriseppstein 
Did you ever found a solution for this? I'm getting the same error now

**Comment by TomiS** [comment]
@fforres Do you, by any chance, use flow typings in your code?

**Comment by fforres** [comment]
Nope 
I can upload a repo with the error if it helps !

**Comment by amiller-gh** [comment]
@fforres That would be very helpful!

**Comment by fforres** [comment]
@amiller-gh https://github.com/fforres/css-blocks-webpack 

To run it `yarn dev`.
Also, if it helps, im running Node `v9.11.1` on a windows machine

**Comment by fforres** [comment]
Circling back!
From what I read here, css-blocks currently does not support webpack4. that was the issue :) 
https://github.com/linkedin/css-blocks/issues/128

**Comment by fforres** [comment]
I updated the code.

running `yarn build` works w/o issues
running `yarn dev` throws: 

```
(node:13154) UnhandledPromiseRejectionWarning: Error: [css-blocks] JSXParseError: Error parsing '/Users/felipetores/Github/fforres/css-blocks-webpack/node_modules/webpack-dev-server/client/index.js?http:/localhost:3000'
Cannot read property '0' of undefined
```
and
```
ERROR in [css-blocks] JSXParseError: Cannot read JSX entry point file /Users/felipetores/Github/fforres/css-blocks-webpack/node_modules/webpack-dev-server/client/index.js?http:/localhost:3000: ENOENT: no such file or directory, open '/Users/felipetores/Github/fforres/css-blocks-webpack/node_modules/webpack-dev-server/client/index.js?http:/localhost:3000' (/Users/felipetores/Github/fforres/css-blocks-webpack/node_modules/webpack-dev-server/client/index.js?http:/localhost:3000)
```

**Comment by nickiaconis** [comment]
I'm encountering this too! Although perhaps this issue is misnamed: the analyzer receives the correct entry point, but it also receives two bogus paths from webpack-dev-server.

webpack-dev-server automatically injects two paths into the entry config: `/ABSOLUTE/PATH/TO/YOUR/PROJECT/node_modules/webpack-dev-server/client/index.js?http://localhost:PORT_NUMBER` and `webpack/hot/dev-server`. Since neither of these paths represent files that actually exist, an error is thrown when the JSX analyzer runs `fs.readFile` on them.

**Comment by fforres** [comment]
Be aware that this only works with Webpack 3.0 @nickiaconis 	
https://github.com/linkedin/css-blocks/tree/master/packages/@css-blocks/webpack#webpack-plugin-for-css-blocks

That was my issue :)

**Comment by nickiaconis** [comment]
@fforres I'm using webpack@^3.12.0

**Comment by nickiaconis** [comment]
@fforres btw what version of webpack-cli are you using? I've been getting peer dependency warnings for webpack-cli, but I can't sleuth what version I'd need to roll back to for compatibility with webpack@3.x, so perhaps that could be related since you say downgrading to webpack@3 worked for you.
