### ISSUE TITLE
How to get started with Bootstrap base style.css?

### ISSUE THREAD

**Issue by johnunclesam** [linkedin/css-blocks#164]
How to get started with Bootstrap base style.css?

**Comment by chriseppstein** [comment]
I assume you're talking about this [bootstrap](https://getbootstrap.com/)?

But I'm not what you mean by "get started with it".

**Comment by johnunclesam** [comment]
Is there a way to optimize the final css code from the default scss?

**Comment by chriseppstein** [comment]
Not as is. CSS Blocks has strong, opinionated constraints on how the css is structured and bootstrap does not adhere to those constraints.

In theory, a port of Bootstrap to CSS Blocks could be done. It would not be a drop in replacement, but it would provide the same UI concepts. The port could still be driven by Sass, but the selectors that are constructed would have to change considerably.

Alternatively, perhaps someone could build a bootstrap specific analyzer and rewriter for use in templates of certain types. Then that could use opticss directly without CSS Blocks as an intermediary. I don't know if that's possible, I suspect there would be considerable challenges to meet the [opticss analysis guarantees](https://github.com/linkedin/opticss/blob/master/docs/ARCHITECTURE.md#analysis-guarantees-and-requirements)
