### ISSUE TITLE
Webpack example is referencing undefined values

### ISSUE THREAD

**Issue by nonken** [linkedin/css-blocks#165]
Looking at https://github.com/linkedin/css-blocks/tree/master/packages/@css-blocks/webpack

`The typical JSX end-to-end integration with webpack looks like this:` is referencing 

```const CssBlockAnalyzer = new CssBlocks.Analyzer(paths.appIndexJs, jsxCompilationOptions);```

where both `paths` and `jsxCompilationOptions` are undefined. `jsxCompilationOptions` is also referenced later in the plugin inclusion definition.

It would be awesome if you could provide a complete end to end example of how to integrate with Webpack or add example values for those properties.

**Comment by nonken** [comment]
Also, on another note: awesome project and work! 🎉

**Comment by chriseppstein** [comment]
Hi @nonken, sorry the example isn't correct. We'll tidy that up.

In the meantime, you can look at how [our website is configured](https://github.com/linkedin/css-blocks/tree/master/packages/%40css-blocks/website/config) or at one of these minimal apps:
 
* https://github.com/matthiaskern/css-blocks-hello-world
* https://github.com/montogeek/css-blocks-webpack-3

**Comment by chriseppstein** [comment]
@nonken is it different? Would you like to send a docs PR?

**Comment by JiiB** [comment]
@chriseppstein Thanks for the links. Is there a create-react-app boilerplate with integrated css-block? I can't get mine to work...

**Comment by bitttttten** [comment]
Is there a way to integrate css blocks without typescript? In your website config, removing typescript support breaks the build.

**Comment by DanielRamosAcosta** [comment]
I'm trying to use `react-create-app` with TypeScript and css-blocks and I feel extremely lost 😢

**Comment by bitttttten** [comment]
The docs are really underwhelming. I could not get it working without using an example repo, but it depends on Typescript and I don't need TS.

@DanielRamosAcosta this is the repo you want: https://github.com/ralfting/boilerplate-css-blocks. It's working very well if you want TS.

**Comment by chriseppstein** [comment]
@bitttttten We want to support projects that don't use typescript. We thought that https://github.com/linkedin/css-blocks/commit/97cd2e46d0c08dbc05b2610ccfa4f4de1793de20 addressed that aspect. Please file a separate issue about typescript being required with details and we'll get it sorted out.

regarding the state of the documentation, we're a brand new project, and so our documentation is certain to miss use cases or be incomplete. That's why this is a developer preview release and not a 1.0. Please help us improve by providing constructive suggestions. Thanks.

**Comment by amiller-gh** [comment]
@DanielRamosAcosta, unfortunately CSS Blocks doesn't work with create-react-app out of the box – you'll need to eject it and customize the Webpack build like we have done in our website's config. There is an open issue (https://github.com/linkedin/css-blocks/issues/114) for adding a CSS Blocks variant to `custom-react-scripts` so you don't need to eject, but we haven't gotten to it yet – contributions are welcome if you have the time! As Chris said, thank you for helping us kick the wheels while we're in pre-1.0 🙂

**Comment by DanielRamosAcosta** [comment]
The PR is #172

**Comment by amiller-gh** [comment]
Closed #172 🎉
