### ISSUE TITLE
Typo in value

### ISSUE THREAD

**Issue by Davidqww** [linkedin/css-blocks#177]
I believe this line 

`{ label: "2", value: "Use your classes and states just regular html", y: 5.0, x: 28 },`

should be corrected to 

``{ label: "2", value: "Use your classes and states just like regular html", y: 5.0, x: 28 },``

on line 87 of code.tsx
[css-blocks/packages/@css-blocks/website/src/pages/Home/components/CodeDemo/demos/code.tsx](https://github.com/linkedin/css-blocks/blob/master/packages/%40css-blocks/website/src/pages/Home/components/CodeDemo/demos/code.tsx)

**Comment by amiller-gh** [comment]
Thanks @Davidqww! Fixed 👍
