### ISSUE TITLE
Question: How to use variables?

### ISSUE THREAD

**Issue by Anenth** [linkedin/css-blocks#179]
How to use variables in these files? 
Is it recommended to use css-variables? 
if so is there any way to import a file globally so that we dont have to import it always in all the files?

**Comment by amiller-gh** [comment]
See https://github.com/linkedin/css-blocks/issues/150 for more details 🙂

I'm going to close this issue as a duplicate for cleanliness' sake, but feel free to keep commenting on the other open tickets. If you have a specific idea for a syntax change to better support some of these use cases, feel free to open up another issue with the proposal!
