### ISSUE TITLE
Website: Color code typo on the home page

### ISSUE THREAD

**Issue by flawyte** [linkedin/css-blocks#205]
![1](https://user-images.githubusercontent.com/1585006/46682961-39ac1000-cbef-11e8-858a-5d9b6046a40b.jpg)
![2](https://user-images.githubusercontent.com/1585006/46682962-39ac1000-cbef-11e8-927f-330abd2073a8.jpg)

As you can see on the screenshots above, the hexadecimal code of one color changes between step 1 and step 2, and both colors are completely different so I thought it was probably a typo and that the color is supposed to remain `#ed2651` accross all three steps.

If this is indeed a typo, please let me know and I'll be happy to submit a PR.

**Comment by amiller-gh** [comment]
Oops! Thats certainly an accident – good catch! Glad people are actually reading the documentation 😉 

A PR would be much appreceated

**Comment by flawyte** [comment]
Do you want me to create a new branch? Or `master` is fine?
