### ISSUE TITLE
Usage with utility classes

### ISSUE THREAD

**Issue by kernel-io** [linkedin/css-blocks#299]
I'm wondering how I can (if possible) use this system alongside a library of css utility classes i.e: Tailwindcss. 
I have an ember project set up with postcss and tailwind, and I'd like to use css-blocks as a way to manage my application styles.

Currently it seems like css-blocks runs before the postcss pipeline, so any styles I `@apply`, never actually get replaced. I'm assuming css-blocks and postcss are integrated at different locations (or running on different trees) in the broccoli pipeline. Any pointers would be much appreciated :)

**Comment by kernel-io** [comment]
For prosperity, I've managed to get tailwindcss working by adding a custom postcss preprocessor to the parserOpts.

**Comment by GCheung55** [comment]
@kernel-io I'm interested in using css-blocks with tailwindcss as well.

Would you mind sharing the custom postcss preprocessor?
