### ISSUE TITLE
will css-blocks work with postcss?

### ISSUE THREAD

**Issue by NullVoxPopuli** [linkedin/css-blocks#310]
I want the static analysis and build optimization of css-blocks, but I also want:
 - css variables
 - nesting
 - custom media queries
 - color functions
 - etc?

there is a list of variables and things here: https://www.shoelace.style/source/css/variables.css (I'm using shoelace for my app).

**Comment by chriseppstein** [comment]
CSS Blocks has preprocessor support which includes postcss, as long as the output of the preprocessor is a legal block, it will work as you expect.

In #309 I'm tracking the fact that we should natively support `&` and `@nest` in selectors and validate them correctly, right now css blocks would not handle it.
