### ISSUE TITLE
ember-cli config file promise is not resolved.

### ISSUE THREAD

**Issue by chriseppstein** [linkedin/css-blocks#365]
The `config.search()` method returns a promise, but there's no `await` at

https://github.com/linkedin/css-blocks/blob/master/packages/%40css-blocks/ember-cli/index.js#L285

**Comment by chriseppstein** [comment]
We should add a synchronous mode to the config module.

**Comment by abritinthebay** [comment]
on it 😄

**Comment by abritinthebay** [comment]
Note: due to that transform extensively uses Dynamic Import, making config support sync is... not likely a small task/possible as-is.
