### ISSUE TITLE
`yarn add $repo` won't work without version in package.json

### ISSUE THREAD

**Issue by entendu** [linkedin/css-blocks#377]
```
$ yarn add https://github.com/linkedin/css-blocks
yarn add v1.21.1
[...]
error Can't add "css-blocks-monorepo": invalid package version undefined.
```

**Comment by chriseppstein** [comment]
This isn't supported. For ember applications, you should `yarn add @css-blocks/ember-cli`. And given that our 1.0 release is in beta, I'd suggest `yarn add @css-blocks/ember-cli@next`.
