### ISSUE TITLE
Split @css-blocks/ember-cli into two addons.

### ISSUE THREAD

**Issue by chriseppstein** [linkedin/css-blocks#400]
One for the App and another for Addons (a third for engines?). This will allow the contract between them to be managed more carefully and will also clean up the code considerably.

**Comment by GCheung55** [comment]
Does this mean that blocks defined within an engine will only be included in the engine's CSS?

How would addon's blocks be treated in the following usecases?
* addon is only used in the engine
* addon is used in the host app and engine
