### ISSUE TITLE
Make Glimmer...Glimmer.

### ISSUE THREAD

**Issue by amiller-gh** [linkedin/css-blocks#85]
We have a number of blockers preventing an end-to-end Glimmer/Ember-CLI integration:

 1. We need to augment the `glimmer-application-pipeline` to automagically discover `glimmer-ast-plugin`s delivered via addons in the registry: https://github.com/glimmerjs/glimmer-application-pipeline/issues/141. 
> Note: 
> Plugins must be passed on to their respective compilers in both the `compileTemplatesToJSON`, and `compileTemplatesToBytecode` methods. 
> 
> To un-block Ember integration we will need to add the `glimmer-ast-plugin` registry type to `ember-cli-htmlbars` as well.
 2. We need a `3.2.0` release of `ember-cli-preprocessor-registry` that includes [Robert Jackson's updates to `registry.add`](https://github.com/ember-cli/ember-cli-preprocessor-registry/commit/22379e12919520a86101f0f8ef314b7de43e4352#diff-168726dbe96b3ce427e7fedce31bb0bcL60) so we can actually register the new `ASTPluginBuilder` type.
 3. ~~When [compiling Glimmer templates to bytecode](https://github.com/glimmerjs/glimmer-application-pipeline/blob/master/lib/broccoli/glimmer-app.ts#L254), there doesn't appear to be a way to pass plugins to the `BundleCompiler ` from `@glimmer/app-compiler`.~~ Sorry, just found it. The bundle compiler *does* accept plugins! They go in through [`BundleCompilerOptions`](https://github.com/glimmerjs/glimmer-vm/blob/f04b36b735e40b326a011f7a63c8d0183bf331ea/packages/%40glimmer/bundle-compiler/lib/bundle-compiler.ts#L41), not top level in [`GlimmerBundleCompilerOptions`](https://github.com/glimmerjs/glimmer.js/blob/master/packages/%40glimmer/app-compiler/src/bundle-compiler.ts#L19). This should be fine.

Once these ~~three~~ two updates are in, we should be un-blocks for an end-to-end Glimmer/Ember-CLI integration.

**Comment by Turbo87** [comment]
@amiller-gh is there a rough overview somewhere on what is needed to make this work with Ember projects?

**Comment by amiller-gh** [comment]
@Turbo87, this project tracks Ember CLI integration: https://github.com/linkedin/css-blocks/projects/3

There are a number of un-answered questions still, and I expect to create more tickets soon, but its a start!

#123 and #124 are the easiest to get started on right now.
